### ISSUE TITLE
Docker Services not getting updated with latest images

### ISSUE THREAD

**Issue by ChakshuGautam** [Unified-Learner-Passbook/ULP-devops#5]
When deploying manually or automatically, I found out that some services were not running the `latest` images even though the build succeeded.

See [this](https://stackoverflow.com/questions/44110075/docker-stack-force-recreate-in-swarm-mode-using-compose-file) thread for more details. It seems a force update is required to force swarm to update images.

**Comment by tushar5526** [comment]
https://github.com/Unified-Learner-Passbook/ULP-devops/commit/9eae8e20914d683b489a78b81e83a9a6e0fcff08#diff-ce9169f8fb4bf9455421787732e6ee9d00c2d2ce5df015417e7b0349e3be4188

This was a silly bug after we refactored pipelines. Fixed now. Closing this!
