### ISSUE TITLE
Discord bot setup

### ISSUE THREAD

**Issue by tushar5526** [Unified-Learner-Passbook/ULP-devops#8]

**Comment by Harshil-Jani** [comment]
https://github.com/jenkinsci/discord-notifier-plugin/issues/102

This is some known bug faced by others as well. Maybe we need to find a workaround. And the repo seems inactive so maybe if this hits our priority then finding an alternative solution would be a better choice.

**Comment by ChakshuGautam** [comment]
@tushar5526 can you share the type of messages and when they should be sent on ticket?

**Comment by tushar5526** [comment]
I am planning to have the setup in the following manner.

Code pushed to GH -> Test are run first -> Image is built and pushed to the private registry that we have hosted, also push to docker hub when we make releases -> Trigger deploy job of Jenkins through GitHub Actions which deploys the main branch on the server. 

We will still keep the Jenkins build stage to be used manually and images will now be built on GitHub Actions. 

Notifications on discord should be sent only when a deployment happens successfully. It should send out a message specifying the last commit, branch name (in case we deploy any other branch manually) name and URL of the service deployed if possible.

**Comment by tushar5526** [comment]
> [jenkinsci/discord-notifier-plugin#102](https://github.com/jenkinsci/discord-notifier-plugin/issues/102)
> 
> This is a known bug faced by others as well. Maybe we need to find a workaround. And the repo seems inactive so maybe if this hits our priority then finding an alternative solution would be a better choice.

If we can't use this completely, then we should write a small script that pings the status on discord which Jenkins can call.

**Comment by tushar5526** [comment]
There are a lot of third party tools that acts as a mediatory to send messages to different communication channels. Maybe we can use any of the open source ones if it is there.

**Comment by Harshil-Jani** [comment]
> There are a lot of third party tools that acts as a mediatory to send messages to different communication channels. Maybe we can use any of the open source ones if it is there.

I tried searching, But all I saw were freemium products with trial periods. On top of it, We need to register for their service as a user to do what we can already do without registering. 

Some tools which I found to do this are [Zapier](https://zapier.com/apps/jenkins/integrations/discord), [Meta APIs](https://dashboard.meta-api.io/apis/discord/integrations/jenkins) , [Another Notifying Jenkins Plugin](https://plugins.jenkins.io/notify-events/). 
Let me know, If you find any open source and free to use tool which helps us get things started.

**Comment by tushar5526** [comment]
Oh, then let's create our own python script for now. If we find something later we can swap it in. Use some other discord webhook for testing. Chakshu seems to be busy.

We need to send messages accordingly if a job fails or succeeds. Feel free to add anything helpful in the messages.

**Comment by tushar5526** [comment]
Don't expose the script on the internet. Keep it internal to the server only.

**Comment by tushar5526** [comment]
Discord Notifier is being used. Thanks @Harshil-Jani
